# Drone config file for simple laravel application without testing
#
# VERSION: 1.0.0

kind: pipeline
type: docker
name: deploy-master

trigger:
  branch:
  - master
  - feature/drone-ci

steps:
- name: restore cache
  image: registry.qonvextechnology.com:5000/drillster/drone-volume-cache:latest
  settings:
    restore: true
    cache_key:
    - DRONE_STAGE_NAME
    - DRONE_REPO_OWNER
    - DRONE_REPO_NAME
    - DRONE_REPO_BRANCH
    mount:
    - 'vendor'
  volumes:
  - name: cache
    path: /cache

- name: install php dependencies
  image: registry.qonvextechnology.com:5000/composer:latest
  volumes:
  - name: composer
    path: /tmp
  environment:
    LIBRARY_PATH: /lib:/usr/lib

  commands:
  - composer install --no-dev

- name: rebuild cache
  image: registry.qonvextechnology.com:5000/drillster/drone-volume-cache:latest
  settings:
    rebuild: true
    cache_key:
    - DRONE_STAGE_NAME
    - DRONE_REPO_OWNER
    - DRONE_REPO_NAME
    - DRONE_REPO_BRANCH
    mount:
    - 'vendor'
  volumes:
  - name: cache
    path: /cache

- name: build image
  image: registry.qonvextechnology.com:5000/plugins/docker
  privileged: true
  settings:
    repo: registry.qonvextechnology.com:5000/${DRONE_REPO_OWNER,,}/${DRONE_REPO_NAME}
    tags: master
    cache_from:
    - "registry.qonvextechnology.com:5000/${DRONE_REPO_OWNER,,}/${DRONE_REPO_NAME}:master"

volumes:
- name: composer
  host:
    path: /tmp/composer
- name: cache
  host:
    path: /tmp/drone-cache
