version: "3"

networks:
  laravel-docker:

services:
  nginx:
    image: nginx
    container_name: Pirasso_nginx
    volumes:
      - ./:/var/www/html
      - ./development/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9055:80

  php:
    build:
      context: .
      dockerfile: development/Dockerfile
    container_name: Pirasso_php
    volumes:
      - ./:/var/www/html
